[awpush]
cookies = []
token = "d9801070a9191f1da1a0925c88357fcb"
uid = "12309253"
wss = "wss://andywang.top:3001/ws"

[awpush.filter]
rooms = [48443, 58121, 66634, 74571, 195958, 256432, 284165, 295476, 398166, 785541, 1065100, 1154214, 23030962, 21229753, 22489675]
words = [
  "测试",
  "钓鱼",
  "炸鱼",
  "大航海",
  "上船",
  "舰长",
  "返现",
  "抵用",
  "代金",
  "黑屋",
  "上车",
  "上反船",
  "照",
  "图",
  "素颜",
  "自拍",
  "写真",
  "皂片",
  "开舰",
  "上舰",
  "自画像",
  "封面",
  "取关",
  "好友",
  "给主播",
  "连麦",
  "情书",
  "指导",
  "绘画",
  "水晶兑换码",
  "一局",
  "舰涨优惠卷",
  "一起玩",
  "开黑",
  "尖叫",
  "点歌",
  "总督",
  "提督",
  "胶囊",
  "壁纸",
  "吃席",
  "船长",
  "^\\d+$",
  "写.*名字",
  "给.*美甲",
  "陪打",
  "带.*上.*星",
  "猫片",
  "饮食分析",
  "情感解惑",
  "开舰",
  "开船",
  "兑舰",
  "兑船",
  "看号",
]
