[global]
size = 3

[[endpoints]]
name = "test"
type = "test"
url = "https://just.for.%s.test"
token = "your"

[[endpoints]]
name = "threecats"
type = "turbo"
url = "https://sctapi.ftqq.com/%s.send"
token = "your token"

[[endpoints]]
name = "sam"
type = "turbo"
url = "https://sctapi.ftqq.com/%s.send"
token = "your token"
