[global]
size = 2

[[tasks]]
init = true
pull = "HeartBeat"
push = "threecats"
period = 3600000000000

[[tasks]]
init = true
pull = "EastMoney"
push = "threecats"
period = 30000000000

[[tasks]]
init = true
pull = "EastMoney"
push = "sam"
period = 30000000000
