[global]
size = 0

# [[tasks]]
# init = true
# pull = "HeartBeat"
# push = "threecats_iphoneX"
# period = 3600000000000

# [[tasks]]
# init = true
# pull = "EastMoney"
# push = "threecats"
# period = 1000000000

# [[tasks]]
# init = true
# pull = "EastMoney"
# push = "sam"
# period = 30000000000
