name: Deploy SubCenter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make build
      
    - name: Test
      run: make test
      env:
        TURBO: ${{ secrets.TURBO }}

    - name: Run
      run: make run
      env:
        TURBO: ${{ secrets.TURBO }}
