name: Deploy SubCenter

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 1 * * 1-5"

jobs:

  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make build

    - name: Run
      run: make run
      env:
        TURBO: ${{ secrets.TURBO }}
        A_STOCK: ${{ secrets.A_STOCK }}
